### ISSUE TITLE
Getting type-checking errors on ssr

### ISSUE THREAD

**Issue by sant123** [fluid-js/fluid#1]
Hi, I'm currently getting these type-checking errors when using the ssr module:

<img width="1199" alt="Screenshot 2024-06-19 at 10 40 24" src="https://github.com/fluid-js/fluid/assets/7959437/45451bc5-8bc3-4254-a505-092867cf0ec5">

However the code works good. What I am doing wrong? I'm using Deno v1.44.3

By the way this framework looks amazing. Thank you!!

**Comment by WorriedArrow** [comment]
Working on a fix right now! Sorry about that! Looks like an error given the first argument of a tag can be either props or the first child.

**Comment by WorriedArrow** [comment]
Fixed in [1.0.6](https://jsr.io/@fluid/core@1.0.6). Let me know if it works now!

**Comment by sant123** [comment]
It works now, however I found something else:

<img width="1356" alt="image" src="https://github.com/fluid-js/fluid/assets/7959437/e7f7e1c9-cfd3-464f-9b38-531b4d730ce8">

The type-checking does not notify errors on this code, but it does not work. I suppose I have to spread the array however doing so a type-checking error appears:

<img width="1354" alt="image" src="https://github.com/fluid-js/fluid/assets/7959437/cf5b7ace-4c0f-4f25-af9b-7fed6ed3bbdd">

Although the code works.

**Comment by WorriedArrow** [comment]
Hmm could you send the code in a
```
codeblock?
```

I want to do some digging on that

**Comment by WorriedArrow** [comment]
Actaully, there's a kinda simple way to fix the typechecking but not sure about the TypeError.

I experienced a little bit of that same error myself when writing it originally. Probably just need to `Array.prototype.flat` earlier.

**Comment by sant123** [comment]
Yes sure, this is the code:

```ts
import { render, tags } from "@fluid/core/server";

const { div, h1, h3, ul, li, a } = tags;

const links = [
    { href: "https://github.com/fluid-js/fluid", title: "GitHub" },
    { href: "https://jsr.io/@fluid/core", title: "JSR" },
    { href: "https://github.com/sant123", title: "Santi" },
];

function Hello() {
    return div(
        h1("Hello, Fluid!"),
        h3("Links"),
        ul(links.map((link) => li(a({ href: link.href }, link.title)))),
    );
}

const template = render(() => Hello());

console.log(template);

```

About the `Array.prototype.flat`, that may do the trick 😁

**Comment by WorriedArrow** [comment]
I believe it is fixed in [1.0.8](https://jsr.io/@fluid/core@1.0.8)! Let me know if you have any further issues.

**Comment by sant123** [comment]
It now works!! @WorriedArrow thank you so much, if you can enable Github sponsors I can buy you a coffee ☕ 

Thanks again!!

**Comment by WorriedArrow** [comment]
I'm glad I could help! Donating means a lot to me and really helps me! I just added a sponsor button to the repo.
Thank you so much for your support! ❤️
